test/basetest/hooks.py, test/basetest/task.py, test/basetest/taskd.py, test/basetest/utils.py
The values of `ENOENT` and `ESRCH` are architecture-dependent, so don't assume they're always 2 and 3.
Found using [pydiatra](https://github.com/jwilk/pydiatra).
=> Tests: Don't hardcode errno constants

doc/man/taskrc.5.in
Hi,
This tries to improve the verbose description to make it more clear what is affected by the header/footnote settings. As first time taskwarrior user I was confused what falls under those settings. I'm not entirely happy with the change though, so feel free to improve it.
Regards
Simon
=> Docs: improve verbose description in taskrc.5.in

src/CLI2.cpp, src/Context.cpp, src/DOM.cpp, src/TDB2.cpp, src/TLSClient.cpp, src/TLSClient.h, src/Task.cpp, src/Variant.cpp, src/columns/ColDepends.cpp, src/columns/ColDescription.cpp, src/columns/ColUDA.cpp, src/columns/Column.cpp, src/commands/CmdCalendar.cpp, src/commands/CmdDiagnostics.cpp, src/commands/CmdEdit.cpp, src/commands/CmdInfo.cpp, src/commands/CmdModify.h, src/commands/CmdStats.cpp, src/commands/CmdSummary.cpp, src/feedback.cpp, src/recur.cpp, src/sort.cpp
Replace C-styled `NULL` with `nullptr`, which should be used in modern C++ projects.
This patch was generated by running clang-tidy [modernize-use-nullptr](https://clang.llvm.org/extra/clang-tidy/checks/modernize-use-nullptr.html) check.
=> Use nullptr instead lf C-styled NULL

DEVELOPER.md, INSTALL, README.md
4a929197ae8c32d62a109e1ab063217d0c57c01b introduced C++14 support. After these changes, the build will now terminate unless the compiler supports C++14 dialect. The documentation does not reflect that: this commit updates few reference files to actually say that the building process requires a C++14-compliant compiler.
=> Update notes regarding C++14 support

doc/man/task.1.in
Hello,
I noticed that the urgency attribute is not defined in the man page, this patch adds it.
However I don't know if there are additional unlisted attributes which can be used in filters. If so, please tell me and I'll update the patch.
Regards
Simon
=> Docs: mention "urgency" as possible attribute for filters

src/TDB2.cpp
Implements #2012. The task ID is displayed just before the description when unwaiting. I am happy to work on a more flexible implementation if it's required.
The test suite problems seem to be the same as before the change.
```$ ./problems
diag.t                              1
project.t                           4 …
```
=> Display task ID when unwaiting task

doc/man/task.1.in
Documentation of the default sort method for `task ready` being *started-then-urgent*.
=> doc/man: ready tasks sorted with started tasks 1st

src/commands/CmdBurndown.cpp
Count the number of pending tasks instead of extracting it from the last `(epoch, pending)` pair. The `pending` map cannot contain zero values, so the previous approach did not work when all tasks had already been completed. It also gave slightly inaccurate results because it ignored tasks completed on the current day.
Closes #2007.
**Note**: There are currently a few failing tests, but none caused by or related to this change.
=> TW #2007: Compute number of current tasks correctly

test/CMakeLists.txt
This policy is no longer necessary because CMake issue #16062, which caused incorrect warnings to be shown, has been resolved in 3.11.0.
=> Do not set CMP0037 on CMake 3.11.0 and above

test/project.t, test/variant_subtract.t.cpp, test/wait.t
Fix variant_subtract test case after merging of PR #2095 
Also fixes wait.t to expect correct output
```
project.t                           2
Expected failures:             
dependencies.t                      2
```
=> Fix variant_subtract test case after #2095

src/commands/CmdProjects.cpp, src/commands/CmdSummary.cpp, src/main.h, src/sort.cpp, test/project.t, test/summary.t
This pull request fixes the issue _[TW-1904] wrong order under projects command_ #1917.
The issue arises due to the fact that the ASCII code of the '.' (dot) is bigger than that of the '-' (hyphen). Thus, the latter will be processed first when traversing a map of strings.
If this is to be fixed without major changes to the underlying Table class (of libshared), the (in my opinion, safe) assumption that nobody will use the '=' (equal) sign within project names comes in handy and can be used to replace all '-' occurrences by '=', pushing these project names behind those including '.' due to the higher ASCII code. Once such a name is encountered the substitution is reverted.
This pull request also extends the same functionality to the summary command.
Unit-tests for the working bug fix have …
=> Fix issue #1917 [TW-1904] wrong order under projects command

src/commands/CmdHistory.cpp
In `history` and `ghistory` commands, repeat the smaller units when a larger unit changes.  For example, if January 2019 is displayed immediately after January 2018, re-show the "January" label instead of only showing the year change.
Assume the `history.d` command shows January 1, 2019 immediately after January 1, 2018. This is the case if there was no activity between those dates.
Before this change:
```
Year Month         Day Added Completed Deleted Net
2018 January         1     2         1       0   1
2019                 1     2         1       0   1
```
After this change:
```
Year Month         Day Added Completed Deleted Net
2018 January         1     2         1       0   1
2019 January         1     2         1       0   1
```
There are unrelated failing tests.
=> CmdHistory: repeat unit if a larger unit changes

doc/man/task.1.in, src/CLI2.cpp, src/CLI2.h, src/Context.cpp, test/verbose.t
My primary motivation was to stop task from printing environment variable overrides every time, but ended up fixing a few things around it as well.
* Original Priorities for taskrc/data overrides were
Priority | taskrc file | taskdata directory
-- | -- | --
1(high) | environment variable | environment variable 
2 | command line override | command line override
3 | N/A | taskrc override
4(low) | default | default
This pr changes it so command line has higher priority then environment variable.
command line having higher priority is pretty much standard in most programs.
original behavior also caused two of the tests to fail due to not unsetting the environment variable
* The original behavior was to print `Using Alternate TASKRC/DATA` in the header for each command line override.
This pr …
=> Change taskrc override priority, respect verbose override, refactor.

doc/man/taskrc.5.in, src/Context.cpp
This commit fixes what I believe to be two mistakes in `taskrc(5)`, specifically, the documentation of the `verbose` setting.
I would appreciate if someone more familiar with this setting could review these changes.
=> [WIP] Fix rc.verbose documentation in taskrc(5)

scripts/fish/task.fish
If the user has `alias grep rg` in Fish, completions are going to fail as the meaning of `-E` option is different in `grep` and `rg`. This ensures that completions bypass aliasing.
```
$ cd test && ./problems
Traceback (most recent call last):
File "./problems", line 60, in <module>
with open(cmd_args.tapfile) as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'all.log'
```
Sorry, the tests seem to be broken.
=> Workaround for alias grep=rg in fish

doc/man/taskrc.5.in
As promised in #2116, this reverts one of the changes I made in f6b2a6541c462eab1e89c3bbcb4610eca84ec295.
It looks like `verbose=1` was actually the correct default; I had been using an older version. Sorry!
=> Fix rc.verbose default value in taskrc(5)

src/commands/CmdEdit.cpp
Previously, multiline string UDAs were not preserved when editing
a task via 'task X edit'. String UDAs are now JSON encoded/decoded
during the edit cycle to allow preservation of multiline.
- [X ] Have you run the test suite?
add.t                               1
bash_completion.t                   5
calendar.t                          2
dateformat.t                        1
quotes.t                            2
hooks.on-modify.t …
=> JSON encode/decode string UDAs

doc/man/task-color.5.in
color.pri.none is now color.uda.priority.none
I have tested the above change with TaskWarrior 2.5.1, and it works correctly. The old 'color.pri.none' option does not work.
Not applicable.
=> fix stale reference to empty priority color config

scripts/zsh/_task
This is a complete refinement to the ZSH completion, including:
- No environment leakage - A.K.A global variables.
- All filter attributes are computed on demand.
* This is important in the common case where a project is being added when a new task is added and you want `task project:` to suggest the new project. Up until now, the completion function completed only projects it knew of from the first time the completion function was loaded.
- Added support for UDAs and their labels in addition to normal attributes.
- Removed the now unnecessary hard coded priority completion since this is supported by the UDAs completion.
=> Completely refine zsh completion for 2.5.2

doc/man/taskrc.5.in
The default values didn't match in a couple places, so I corrected those.
add.t                               1
bash_completion.t                   5
dateformat.t                        1
quotes.t                            2
recurrence.t …
=> Some taskrc man page proofreading

test/add.t
The test was failing on my machine on fresh checkout. It failed because
somehow both new-id and new-uuid verbosity were set during the test, so
TW defaulted to printing out uuid, which did not match the assertion.
Test fixed by explicitly setting verbosity to new-id.
Replace this text with a description of the PR.
=> Fix add.t Test1549 test failure.

src/commands/CmdCalendar.cpp
As far as I can see, this should be everything that is necessary to fix the bug described in #1997 
```
add.t                               1
bash_completion.t                   4
dateformat.t                        1
tw-1999.t …
```
=> Fix report colors in calendar - Issue #1997

scripts/zsh/_task
This is the same as how the `_task_zshids` array is created.
See https://github.com/ohmyzsh/ohmyzsh/issues/8249
This PR doesn't need to run the test suite. I have tested it manually with the following steps:
1. Use zsh with the completion file loaded
2. Create the task projects: `task add TEST project:"Test Project"`
3. Try to complete: `task project:[TAB]`
=> Correctly parse projects with spaces in zsh completion

src/ViewTask.cpp, src/text.cpp
This addresses #2023
For many years linewrap has been broken in taskwarrior, rendering the
application basically useless in terminals with short widths and tasks
containing URLs in them... This janky line wrap patch sort of works but
introduces other minor graphical glitches.
But seeing as no one took the time to fix it over the years, here some a
small salvation to those who suffer as much as me.
One problem of this patch is, when a line is wrapped, it may be 1 column
smaller than the terminal width, resulting in each line not fully
utilizing the terminal width.
This patch is not polished and could probably need to be tended by
someone who cares more.
This patch has been tested on v2.5.2
=> Poor implementation of linewrap restored to task

src/TDB2.cpp
Call onModify hook when running task undo. Changes from the hook are ignored.
=> hook onModify into task undo (Closes: #2213)

scripts/CMakeLists.txt
zsh by default includes `$PREFIX/share/zsh/site-functions` in `$fpath`. Install the zsh completer there so that it is automatically picked up. 
I've tested the change through OpenBSD's ports.
=> Install zsh completer to site-functions

doc/man/task.1.in
The example for _unique has typo, should be using attribute for project.
Fixes #2277
I opted to skip tests, given the scope of the change.
=> Fix typo in man page example

test/quotes.t
The test was failing because it expected "Created task 1"
but it saw "Created task 0a436fd8-7f06-4168-a66d-bbc940498af9".
Instead, the new code looks at the description of task 1.
Replace this text with a description of the PR.
Before this PR:
> quotes.t                            2
After this PR:
> quotes.t                            1
=> Fix TestBug1436's failure due to task number vs. hash

src/Task.cpp, test/substitute.t
I stumbled upon a SIGSEGV when I tried substituting a sequence in a task description with a shorter one.
```sh
$ task add aaaaCaaaa
Created task 1.
$ task 1 modify /aaaa/b/g
(SIGSEGV)
```
I fixed the bug and added a unit test for it.
```
tw-1999.t                           1
undo.t                              2
version.t                           2 …
```
=> Fixed SIGSEGV when substituting a sequence in a task description with shorter one

src/recur.cpp
Due to not accounting for the leading "P", getNextRecurrence would always return the same datetime, breaking all generic "PnM" periods and leading to an infinite loop in generateDueDates.
All credit for the discovery of this bug goes to Michał Mirosław, who reported this and provided a patch in [this Debian bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=951776); this is also why I backdated the author date to that bug report. I opted not to include the `if (increment <= 0)` part of the patch because that is a different and unrelated issue (#2262): an infinite loop in `generateDueDates` and caused only by (this bug and) weird, nonsensical periods of length zero, e.g. `P0M` .
Given that this bug was not caught earlier, it would also be good to add tests for this recurrence parsing, …
=> Fix parsing of "PnM" recurrence periods

src/commands/CmdDelete.cpp, src/commands/CmdModify.cpp
Fix #2325
Fix #2309 
Make delete and modify commands only prompt about propagating changes to children when rc.recurrence.confirmation is set to 'prompt'.
* Passes all in `make test`
=> Make modify and delete commands respect rc.recurrence.confirmation config option. #2309 #2325

src/TLSClient.cpp
POSIX tells us that it is errno.h, musl fails to build with -Werror
because it redirects sys/errno.h->errno.h and uses `#warning`
=> Uncoditionally include errno.h instead of guessing

test/lexer.t.cpp
```
$ task 0000000d-000a-0000-0000-000000000000 export
Cannot subtract strings
$ task 0000000d-0000-0000-0000-000000000000 export
The expression could not be evaluated.
```
=> Test: Add UUID test demonstrating a "Cannot subtract strings" bug

src/Variant.cpp, test/diag.t, test/project.t, test/variant_subtract.t.cpp, test/wait.t
This PR backports some of the test fixes already present on the 2.6.0 branch onto the 2.5.2 branch.
It also fixes some other details in the tests which were outdated.
```
% ./problems
Failed:
```
The above failures are still related to the following problems:
=> Fix tests on 2.5.2 branch

src/feedback.cpp
A while ago I noticed that 630a1530e0e0495f602ec5b687630b54945b2882 only added the QUARTER virtual tag to src/Task.cpp, and when I checked that again today, it was still missing from src/feedback.cpp, so I'm fixing that.
(not expecting any breakage, so I'll leave this to the CI)
=> Add missing "QUARTER" to feedback_reserved_tags

doc/man/task.1.in, src/TLSClient.cpp
#2223, #2280, #2320 were merged to master but not to 2.5.2 nor 2.6.0.
This PR cherry-picks #2280 and #2320 to 2.5.2.
PR #2223 is skipped for two reasons:
1. most commands now use Table instead of ViewTask, so the benefit of the change is quite limited
2. it really is a quick dirty hack that needs more review/work before being merged
=> Cherry-pick PRs accidentally merged to master into 2.5.2

src/ViewTask.cpp
This reverts commit 64243e6ec1919e5ce41f95b00cffe8b263ebb980 which was introduced by #2223.
As discussed in #2345 there is one final test on the 2.5.3 branch which is failing. This test is passing fine on 2.6.0 and also used to pass fine on 2.5.2 because the failure is caused by #2223 which was merged into `master` directly (which 2.5.3 is now based on).
#2223 attempted to fix #2023 by introducing a workaround to handle linewrapping. However, since the 2.5.2 release most commands now actually use a table rather than `ViewTask` (thanks @liskin).
Thus, reverting 64243e6 does not actually cause any problems as shown below:
```
% ./run_all
Passed:                          3776
Skipped:                            5 …
```
=> Fix final failing test on 2.5.3

doc/man/task.1.in, doc/man/taskrc.5.in, src/CLI2.cpp, src/CLI2.h, src/Context.cpp
Implements [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
Motivation: https://farbenmeer.de/de/blog/the-power-of-the-xdg-base-directory-specification
I'm aware of [this PR](https://github.com/GothenburgBitFactory/taskwarrior/pull/2248) already being open. But it looks like it doesn't implement the full spec and seems to be going into limbo, so I gave this a shot.
With these changes, taskwarrior still supports the current file locations, but make the new locations the default for new users. As suggested by @corbolais [here](https://github.com/GothenburgBitFactory/taskwarrior/pull/2316#discussion_r467478464), if files exist in both old and new locations, taskwarrior will print a warning and uses the old locations.
This is the …
=> Xdg basedir spec

src/commands/CmdEdit.cpp, src/commands/CmdEdit.h
Since e4b9c1f annotations where JSON encoded in task edit to escape
new lines (\n). But other strings where mangled as well, like https://
becoming https:\/\/, making it hard to edit.
This patch removes the JSON encoding and indents new lines instead.
Failed:
Skipped:
dependencies.t                      2
filter.t                            4
project.t …
=> Support editing multi-line annotations (Closes: #2283)

src/commands/CmdEdit.cpp
=> fix: remove lock file on interruption of 'task edit' (#2292)

ChangeLog, NEWS, src/Variant.cpp, src/columns/ColTypeDate.cpp, test/dependencies.t, test/filter.t, test/variant_cast.t.cpp, test/variant_gt.t.cpp, test/variant_gte.t.cpp, test/variant_lt.t.cpp
This MR brings several improvements and fixes to the handling of Duration types in the Variant object:
* The relative duration values (such as `7d` or `P1M`) are anchored with respect to `now` during casting to `type_date`
* Durations can now be up to ~ 1 million years
* Tests are adjusted accordingly
Closes #1654, #2390.
=> Improve Variant handling of Durations

ChangeLog, src/Lexer.cpp, test/dependencies.t, test/tw-2392.t
Prevent zero-leading integers from matching.
Closes #2392.
=> Restrict Lexer's integer and number detection

ChangeLog, NEWS, src/commands/CmdCalendar.cpp
The purpose of displaying due dates on the calendar is to convey the relative business of any given day. Waiting status signifies a task should not be displayed in reports yet, but for the purposes of planning, it should be displayed in the calendar overview.
Additionally improves calendar range and defaults.
Closes #2393.
=> CmdCalendar: Consider waiting due tasks

scripts/bash/task.sh, test/bash_completion.t, test/bash_tap_tw.sh
Previously, if the path of the repo had spaces in it (eg "~/Documents/Open Source/taskwarrior"), some of the test scripts would fail. This was due to the bash variables representing the binary not being correctly dereferenced as strings, which lead to bash interpreting the path as two arguments instead of one. The affected scripts have been updated to treat the binary as a string and should operate correctly regardless of special characters in the path.
The version test is currently failing upstream of my changes.
dependencies.t …
=> Bash paths correctly dereferenced to account for spaces

src/CMakeLists.txt
these libararies are not installed so don't leave the decision up to
enviroment which might build shared libraries resulting in binary
with missing deps after installation
Fixes #2403
=> build: make sure internal libs are built as static

ChangeLog, NEWS, src/CLI2.cpp, src/CLI2.h, src/columns/ColTypeString.cpp, test/filter.t, test/project.t, test/search.t, test/tw-1883.t, test/tw-1895.t, test/tw-2257.t, test/tw-2386.t
This MR implements more restricted behaviour when evaluating and desugaring filter string attributes, namely:
* Filtering for string attribute values with spaces is supported (#2388)
* String attribute values now can start with reserved keywords (#1908, #2257)
Also implements support for dealing with empty parentheses expressions, see #1896.
Closes #2388.
Closes #2386.
Closes #2257.
Closes #1908.
Closes #1896.
=> Restrict evaluation of string attributes, support empty paren expressions and other parser improvements

test/bash_tap.sh, test/tw-2124.t
Bash-tap tests can now run in expected-failure mode, which means writing a test case for a feature that is currently failing, is as simple as:
```
#!/bin/bash
. bash_tap_tw.sh
export EXPFAIL=true
task add test +one-two
task +one-two list
```
A test for TW #2124 is added as demonstration.
=> Implement expected failures for bash tap tests

src/TDB2.cpp, src/Task.cpp, test/lexer.t.cpp, test/t.t.cpp, test/tdb2.t.cpp
Found with modernize-raw-string-literals
```
Passed:                          3789
Skipped:                           12
Expected failures:                 13
Runtime:                        38.38 seconds
[100%] Built target test
```
=> clang-tidy: use raw string literals

ChangeLog, src/commands/CmdEdit.cpp
Since 'task edit' is a data-modification operation (that is particularly hard to cancel mid-way), it should also respect the 'bulk' option like all the other modification operations (mod, start...).
Closes #2428.
=> CmdEdit: Respect bulk option

src/commands/CmdDone.cpp
The behaviour for batch-completing tasks irritated me, because task nagged every time there were more than one task was completed.
This PR fixes this and makes the done command a little faster because nag is only called once.
Output of ```cd test && ./problems```:
```
Failed:
template.t                          3
tw-1999.t                           1
Skipped:
feature.default.project.t           3
template.t                          2
tw-1999.t                           1
dependencies.t …
```
=> Change nagging behavior

src/Context.cpp
`context` was not included among the possible verbosity tokens, resulting into the `verbose` setting being incorrectly set to `off` in some cases.
=> Parse 'context' verbose token correctly

ChangeLog, src/CLI2.cpp, test/tw-2451.t
This ensures that substrings of named dates can be used as search strings for description field.
Closes #2451.
=> Desugar plain arguments of Lexer::type::date type

.github/workflows/tests.yaml
This reverts commit 17ab0dfcf4b3bdfa1d710891b00e347b9841ec75.
The underlying issue with the Arch Linux was fixed, see references in the above commit for more details.
=> ci: Re-enable testing on Arch Linux

src/CLI2.cpp, src/Lexer.cpp, src/ViewTask.cpp, src/commands/CmdInfo.cpp
Found with performance-faster-string-find
- [x ] Have you run the test suite?
```
Failed:
Skipped: …
```
=> clang-tidy: use '' for single character find

src/Lexer.cpp, src/recur2.cpp
Found with modernize-use-bool-literals
- [ x] Have you run the test suite?
```
Failed:
Skipped:
tw-2124.t                           1
```
failure looks bogus.
=> clang-tidy: use bool literals

src/Hooks.cpp, src/columns/ColDepends.cpp, src/commands/CmdIDs.cpp, src/feedback.cpp
Found with performance-inefficient-vector-operation
- [x ] Have you run the test suite?
```
Failed:
Skipped:
tw-2124.t                           1
```
probably a bogus failure.
=> clang-tidy: add missing reserve calls

src/Task.cpp, src/feedback.cpp
Found with performance-for-range-copy
=> clang-tidy: use const references

src/CLI2.cpp, src/CLI2.h, src/DOM.cpp, src/Eval.cpp, src/Task.cpp
This set of changes improves performance by 2-10x depending on the data and command issued:
Previously:
```
$ time bash -c 'for i in `seq 1 100`; do task2.6.0 project:Work -random count > /dev/null; done'
real	0m12.698s
user	0m12.326s
sys	0m0.348s
```
After:
```
time bash -c 'for i in `seq 1 100`; do task project:Work -random count > /dev/null; done'
real	0m1.684s
user	0m1.365s
sys	0m0.316s
```
=> Improve performance 2-8x

src/Filter.cpp
This ensures we don't need to load the `completed.data` when the query only concerns pending tasks. The mechanism is not perfect, but it should serve as a good enough patch for now.
Closes #2201.
=> Consider +PENDING as +ACTIVE as triggers for pendingOnly shortcut

src/commands/CmdCount.cpp, src/commands/CmdStats.cpp, src/feedback.cpp
Simpler and generates less assembly.
=> convert manual loops to std::count_if

src/TLSClient.cpp
Haiku uses errno.h instead of sys/errno.h.
See comment below
=> Fix reference for errno.h on Haiku

CMakeLists.txt
We need libnetwork on Haiku for socket(), setsockopt() ...
Used `-DCMAKE_EXE_LINKER_FLAGS=-lnetwork` before, but this patch makes that obsolete.
=> Search for libnetwork on Haiku

test/dateformat.t
Add a test for capitalized months and days of the week.
The change was implemented in
https://github.com/GothenburgBitFactory/libshared/pull/33.
This change adds validation in TaskWarrior.
Fixes:
* https://github.com/GothenburgBitFactory/taskwarrior/issues/2160
* https://github.com/GothenburgBitFactory/taskwarrior/issues/2364
See https://github.com/GothenburgBitFactory/tw.org/pull/111 for documentation update.
```
$ ./run_all     
Passed:                          3794
Skipped:                           12
Expected failures:                 13
Runtime:                        16.25 seconds
```
```
$ …
```
=> Add a test for capitalized months and days of the week.

src/commands/CmdDiagnostics.cpp
This message does not really help, and makes the binary non-deterministic.
=> Remove build date/time from diagnostic message

doc/man/task-color.5.in, doc/man/taskrc.5.in, src/Context.cpp
Support relative include for themes in taskrc. Fix #1847.
This is required for package manager like nix, which installs different version of a package to different paths. We need to keep paths of `include` in taskrc to be always valid between updates.
This PR depends on https://github.com/GothenburgBitFactory/libshared/pull/38 to be merged.
All tests passed.
=> Support relative include for themes in taskrc

test/quotes.t, test/tw-1883.t, test/tw-1895.t, test/tw-2124.t, test/tw-2257.t, test/tw-2386.t
- Prefer `/usr/bin/env` in shebangs, since `bash` may not be installed in `/bin` in some systems (like NixOS). And we already use `/usr/bin/env` in most of scripts.
- Use `echo` from `PATH` instead of hard-coded `/bin/echo`, for the same reason.
=> Prefer /usr/bin/env and searching from PATH

ChangeLog, src/commands/CmdExec.cpp
Closes #2503. This should prevent some unnecessary confusion.
=> CmdExec: Prevent user from executing an empty command

ChangeLog, src/Variant.cpp, test/variant_partial.t.cpp
The code handling the comparison between the date and string types would
convert the variants to correct types, but only through multi-level
fall-through in the switch statement, which is always a bit of a
dangerous construct.
Added explicit return for the non-trivial case, preventing the need for
the fall-through.
Also added some tests to ensure this works correctly (even though this
was technically working correctly before this fix as well).
Closes #2502.
=> Variant: Do not use implicit fall-through in operator_partial

ChangeLog, NEWS, scripts/reproduce-dockerfile, src/Task.cpp, test/tw-1804.t
This relaxes previous stringent requirements on the input attributes of annotations during import. In particular, annotations that have a missing "entry" value can still be imported - the current time will be assumed.
Also prevents a segfault when importing an annotation without a description.
Closes #1804.
=> parseJSON: Allow annotations with missing entry values

AUTHORS, ChangeLog, src/feedback.cpp, test/tw-2514.t
Instead of relying on the modification times, we can use the values of
the start and end attributes, if available.
This allows us to perform historical changes that result in correct
duration intervals reported by task info.
Closes #2514
=> feedback: Consider start and end attributes when reporting task durations

AUTHORS, ChangeLog, NEWS, test/math.t
This was the behaviour implemented in TW 2.5.1 and before.
Closes #2519.
=> All 'end of' named dates should point to the last second of the referenced interval

ChangeLog, test/tw-2530.t
Regression #2530 occurred in 2.5.3, fixed in 2.6.0. This tests makes sure we have this case covered in the suite.
Closes #2350.
=> tests: Add a regression test for #2530

src/Task.cpp, src/commands/CmdInfo.cpp
`~/.taskrc`
```
urgency.user.project.work.coefficient=2.0
urgency.user.project.workout.coefficient=1.0
```
```
$ ~ task project:workout add 'Evening working out'
Created task 13.
The project 'workout' has changed.  Project 'workout' is 0% complete (2 of 2 tasks remaining).
$ ~ task 13
No command specified - assuming 'information'.
Name          Value
ID            13
Description   Evening working out
Status        Pending
Project       workout
Entered       2021-07-07 21:18:19 (1s)
Last modified 2021-07-07 21:18:19 (1s)
Virtual tags  LATEST PENDING PROJECT READY UNBLOCKED
UUID          5432f1b1-5a4b-4129-a947-f7da6e30d0f2
Urgency          3
PROJECT work         1 *    2 =      2
PROJECT workout      1 *    1 =      1
------
3
```
As you can see, while `Project` line correctly assumes, …
=> Fix matching project name during urgency calculation

AUTHORS, ChangeLog, NEWS, doc/man/task.1.in, src/CLI2.cpp, src/Context.cpp, test/due.t, test/filter.t
Adds the modifier 'by' to those possible for filter attributes.  This uses `<=` for comparison rather than `<` as the existing `before` modifier does.  Includes docs, tests and credit.  Also added a test for #2519 which isn't technically part of this patch per se, but was the genesis and is related so it makes sense to include it in this PR.
See #2519 for full discussion and #2536 for the issue this PR closes.
```
$ ./problems
tw-1999.t                           1
Expected failures:             
lexer.t …
```
=> Add filter attribute modifier 'by'

src/commands/CmdAnnotate.cpp, src/commands/CmdAppend.cpp, src/commands/CmdDelete.cpp, src/commands/CmdDenotate.cpp, src/commands/CmdDone.cpp, src/commands/CmdModify.cpp, src/commands/CmdPrepend.cpp, src/commands/CmdStart.cpp, src/commands/CmdStop.cpp
Added number of tasks as output for batch operations, see issue #2532.
Passed:                          2717
Skipped:                            0
Expected failures:                  4
Runtime:                         0.35 seconds
=> Added output of number of tasks to be modified in batch mode

ChangeLog, src/Context.cpp, src/commands/CmdCalendar.cpp, src/commands/CmdShow.cpp
Color can be defined by color.calendar.scheduled, see issue #2208 
Passed:                          2717
Skipped:                            0
Expected failures:                  4
Runtime:                         0.35 seconds
=> Added coloring of scheduled dates in calendar report

src/commands/CmdInfo.cpp
This patch fixes a cosmetic issue that would cause run-on tag names to be shown in the output when viewing a task and displaying its list of virtual tags.  Some lines were missing spaces, because their virtual tag definitions did not include a space like all the rest, and these spaces were relied on for output formatting.
> Have you run the test suite?
Have not run the test suite; presumably this is a cosmetic change.  Did test the fix itself and it does make the run-on tags disappear.
=> CmdInfo: fix missing spaces causing run-on in virtual tag list

src/commands/CmdDone.cpp, src/commands/CmdStart.cpp, src/main.h, src/nag.cpp, test/nag.t
With this patch, taskwarrior uses the urgency of tasks before any
modifications are applied when deciding whether to show nag messages.
Previously, taskwarrior would apply modifications before deciding
whether to show nag messages, which could lead to spurious nag messages
when completing an active task.
Fixes #2163.
- [x ] Have you run the test suite?
```
Failed:
Skipped:
tw-1999.t                           1 …
```
=> Nag based on task state before modification

ChangeLog, NEWS, test/verbose.t
=> Tests to cover rc.verbose:nothing order invariance

src/CLI2.cpp, src/Eval.cpp, src/Filter.cpp, src/TDB2.cpp, src/Task.cpp, src/ViewTask.cpp, src/commands/CmdEdit.cpp, src/commands/CmdGet.cpp, src/sort.cpp, test/lexer.t.cpp
Allows removing the constructor name as emplace forwards the arguments
directly.
=> use emplace

src/Task.cpp, src/Task.h, src/columns/ColTags.cpp, src/commands/CmdEdit.cpp, src/commands/CmdInfo.cpp, test/tag.t
Each tag is stored as `tag_<tagname>: x`.  The `x` is required because
empty attributes are treated as nonexistent.
For compatibility, the `tags` attribute is updated in sync with the 
per-tag attributes.  This compatibility support may be dropped in later
versions.
Note that synchronization _updates_ use JSON format, which does not 
change with this patch, and thus no compatibility issues exist.  The 
synchronization _initialization_, however, uses FF4, meaning that a
sync server initialized from a version of `task` with this patch will
contain `tag_<tagname>` attributes, which will look like orphaned UDAs
to older versions.  However, as updates to tasks are synchronized via 
the sync server, the updates will not contain these attributes and they
will show as "deleted" in the `task info` …
=> Refactor to store tags as individual attributes

ChangeLog, NEWS, src/CLI2.cpp, test/tw-2550.t
The purpose of this break is to not apply the context on commands like
task 4 info
so that we can still refer to tasks directly (using their ID/UUID
references) even if they fall outside of the currectly active context.
However, this break should not be applied for writeable context. This is
because the lexer can (a bit misleadingly) label parts of the desription
of the new task as number/identifier tokens
task add Replace 3 parts of the puzzle abc123
^                     ^
type::number          type:uuid
which would trigger the break unnecessarily.
Closes #2550.
=> CLI2: Apply UUID/ID context break only for readable context

ChangeLog, doc/man/taskrc.5.in, src/Context.cpp, src/TDB2.cpp, src/Task.cpp, src/Task.h, src/columns/ColDepends.cpp, src/commands/CmdEdit.cpp, src/commands/CmdInfo.cpp, src/commands/CmdPurge.cpp, src/commands/CmdShow.cpp, src/dependency.cpp, src/feedback.cpp, src/main.h, src/sort.cpp, test/export.t, test/import.t
This also drops support for the transitional `json.depends.array` configuration value, which has not been necessary since ~2016.
As with tags, dependencies are stored in both a "combined", comma-separated format (for compatibility) and in an attribute-per-dependency format (for the future).
The first commit in this PR takes pains to prevent direct access to the `depends` attribute, although two places will be handled in #2572.
=> Refactor to store dependencies as individual attributes

ChangeLog, src/commands/CmdConfig.cpp, test/tw-2581.t
Trailing comments previously caused crash of the application.
Closes #2581.
=> CmdConfig: Properly preserve comments at the end of the line

src/Task.cpp, test/import.t
Check annotations field before parsing
Add test case for annotations
```
Failed:
delete.t                            2
urgency.t                           1
Skipped:
filter.t                            1
nag.t                               5
tw-2124.t …
```
=> Fixes #2580

test/filter.t
This is already fixed on 2.6.0 thanks to #2405, but it never hurts to have more tests.
=> Add test for TW #2577

ChangeLog, src/CLI2.cpp, test/tw-2189.t
Before, the parser always escaped single quotes, independent of the quotes being escaped already. This is now fixed. This should fix #1960  and #2189 .
```
Passed:                          3817
Skipped:                           18
Expected failures:                 13
Runtime:                        11.25 seconds
```
=> Fixed bug with double escaped single quotes

src/commands/CmdCustom.cpp, src/commands/CmdExport.cpp, src/commands/CmdExport.h, test/tw-2575.t
This PR adds allows using filter and report when running `task export`. This PR uses the `filter` and `sort` from the `rc.report` value.
```bash
$ task <filter> export [<reportname>]
```
The following are all valid export commands:
```bash
$ task export
$ task export next
$ task +WAITING export next
$ task +PENDING export customreport
```
This will resolve #2575. This also provides a more cleaner alternative to #2177.
```
$ cd test && ./problems                                                                   
Failed:
Skipped: …
```
=> Support `task <filter> export [<reportname>]`

src/Task.cpp
This prevents `tag_*` and `dep_*` attributes from being identified as orhpan UDAs in the output of `task edit`.
=> Make sure tag and dependency attributes are not identified as orphan UDAs

doc/man/taskrc.5.in, src/commands/CmdBurndown.cpp, test/burndown.t
This should fix #1914
Output before implementing the feature and according test:
```bash
Failed:
template.t                          2
Skipped:
filter.t                            1
nag.t                               5
template.t                          3 …
```
=> Implement non-cumulative config option for burndown command

src/commands/CmdHelp.cpp
Previously the `task help` command gave this output:
```text
Alternately algebraic expressions support:
and  or  xor            Logical operators
<  <=  =  !=  >=  >     Relational operators
(  )                    Precedence
task due.before:eom priority.not:L   list
task '(due < eom or priority != L)'  list
```
The last two lines are not equivalent; this PR changes the word `or` in the last line to `and`:
```text
task due.before:eom priority.not:L   list
task '(due < eom and priority != L)'  list
```
=> fix a typo in the help commnad

src/ViewTask.cpp, test/hyphenate.t
This allows `task` to handle situations when one or multiple columns contain extremely long words, such as URLs:
```
$ task add https://github.com/GothenburgBitFactory/taskwarrior/compare/handle_neg_overage?expand=1https://github.com/GothenburgBitFactory/taskwarrior/compare/handle_neg_overage?expand=1
Created task 1.
The project 'Inbox' has changed.  Project 'Inbox' is 0% complete (1 task remaining).
$ task 1 annotate https://github.com/GothenburgBitFactory/taskwarrior/compare/handle_neg_overage?expand=1https://github.com/GothenburgBitFactory/taskwarrior/compare/handle_neg_overage?expand=1
Annotating task 1 'https://github.com/GothenburgBitFactory/taskwarrior/compare/handle_neg_overage?expand=1https://github.com/GothenburgBitFactory/taskwarrior/compare/handle_neg_overage?expand=1'. …
```
=> ViewTask: Handle negative overage by decreasing size of the largest columns

README.md
Added GnuTLS and libuuid to build dependency list in the README. I noticed they were on [this page](https://taskwarrior.org/docs/first_time.html), but not in the README where people look first.
Test suite ran with no unexpected failures.
=> add library build dependencies to README

ChangeLog
This PR updates `ChangeLog` file to mark the latest version which is `2.6.0`.
(I used UTC time for the date.)
> - [ ] Have you run the test suite?
I don't think running the tests is necessary for this change.
=> changelog: mark 2.6.0 as current release
