GothenburgBitFactory/taskwarrior

- DEVELOPER.md
Rough markdownification, no content changes
> Update to markdown and rename DEVELOPER to DEVELOPER.md

- doc/man/taskrc.5.in
typo -> very simply syntax -> very simple syntax
> fix small typo in taskrc's man page

- scripts/vim/ftdetect/task.vim
> Updates vim's ftdetect

- src/Variant.cpp
Fixes #1537 (previously known as TW-1511).
> TW-1511: Interpret string subtraction as concanetation with a dash

- src/Task.cpp
Make the comment on Task::decode match reality.
> Docs: make comment on Task::decode match reality

- src/commands/CmdTimesheet.cpp
Signed-off-by: Me <corbolais@gmail.com>
I find it quite useful to have the ID included in the timesheet report. This alleviates the need to specifically look up IDs for the tasks in question.
Thank you for taskwarrior in the first place. My life feels so much more organized now. Less post-it's, less paper notes, more _one place to rule them all_. Thanks.
- [X ] Have you run the test suite?
make test fails:
```
[ 95%] Linking CXX executable col.t
/usr/bin/ld: ../src/columns/libcolumns.a(Column.cpp.o): in function `Column::uda(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Column.cpp:(.text+0x340): undefined reference to `Context::getContext()'
```
> add (shortened) ID column to timesheet output

- DEVELOPER.md
This fixes a small typo. There is no directory "tests".
I could not find information on where pull requests should go in general. So I choose the master branch.
> fix typo ("tests" -> "test")

- doc/man/taskrc.5.in
I found the ordering and labelling of the calendar sections to be confusing, so I'm proposing this reorganisation.
add.t                               1
bash_completion.t                   4
dateformat.t                        1
quotes.t                            2
import.t …
> Proposed taskrc(5) reorganisation

- scripts/fish/task.fish
The speed up comes from making things static if possible (e.g. the taskw _commands) are static so it shouldn't invoke it everything it wants to check for present of command.
It also avoids for-loop echo if possible, and it store the list of modifier in variables.
It also micis zsh's autocompletion by replicating it's autocomplete, and made fish's completion for `tags` and `project` only invoked when `+`, `-` and `project:` are presents (to avoid cluttering the screen with tags and avoid computational overhead)
> Speed up fish autocompletion and more completion options

- src/commands/CmdPurge.cpp
Prompted by the failure mode described by Glen Solsberry in #2254.
> CmdPurge: Detect the failure mode of trying to purge non-deleted tasks

- scripts/hooks/README
Mention `task diagnostics` to debug hooks location
> Hooks readme : mention `task diagnostics` debug

- AUTHORS
- ChangeLog
- NEWS
- doc/man/task.1.in
- src/CLI2.cpp
- src/CLI2.h
- src/Context.cpp
- src/Context.h
- src/commands/CmdAdd.cpp
- src/commands/CmdContext.cpp
- src/commands/CmdLog.cpp
- test/commands.t
- test/context.t
Support for context for the `add` and `log` commands.
Closes #1955.
> Implement writeable context

- doc/man/taskrc.5.in
- src/commands/CmdCalendar.cpp
- test/calendar.t
This PR resolves #1911 and cleans up the code for holiday colorization.
Output of test/problems:
```errors
Failed:
template.t                          2
Skipped:
template.t                          3
template.t …
```
> Implement multi-day holidays

- src/commands/CmdCalendar.cpp
> CmdCalendar: Only display relevant parts of the legend

- .github/workflows/tests.yaml
- NEWS
- docker-compose.yml
- test/docker/fedora34
- test/docker/ubuntu2104
Adds Fedora 34 and Ubuntu 21.04 into the CI matrix.
> Expand tested configurations to include newest Ubuntu / Fedora releases

- src/Hooks.cpp
- src/Task.cpp
- src/commands/CmdBurndown.cpp
- src/commands/CmdImport.cpp
> clang-tidy: use auto

- src/Context.cpp
- src/Eval.cpp
- src/ViewTask.cpp
- src/commands/CmdCalendar.cpp
- src/dependency.cpp
- test/lexer.t.cpp
Found with modernize-loop-convert
> clang-tidy: loop conversion

- ChangeLog
- src/columns/ColTypeDate.cpp
- test/columns.t
Fixed countdown column counting in the wrong direction, see #1840 
Passed:                          2717
Skipped:                            0
Expected failures:                  4
Runtime:                         0.38 seconds
> fixed rendering of countdown columns

- .github/workflows/tests.yaml
- ChangeLog
- NEWS
- test/project.t
Adds test that make sure we don't regress on the issue in #1913 in the future.
> Add tests for TW #1913

- src/CLI2.cpp
- src/CLI2.h
- src/commands/CmdContext.cpp
- test/context.t
> Detect invalid write context and warn the user

- DEVELOPER.md
- NEWS
- doc/man/task.1.in
- doc/man/taskrc.5.in
This PR implements a broad-sweeping update of the documentation to ensure that the changes shipped in 2.6.0 are properly reflected.
> Update documentation for the 2.6.0 release

- ChangeLog
- NEWS
- doc/man/taskrc.5.in
- test/project.t
This is a followup on the previous MR #2606, which got accidentally merged.
> Second batch of release documentation updates

- CMakeLists.txt
- src/Context.cpp
- src/commands/CmdShow.cpp
- test/basetest/task.py
- test/version.t
Minor adjustments to tests and cmake config to ensure correct tarball builds.
> Final tweaks for the 2.6.0 release

- doc/man/task.1.in
- scripts/fish/task.fish
- scripts/zsh/_task
- src/TLSClient.cpp
- src/Task.cpp
- src/commands/CmdInfo.cpp
- src/commands/CmdTags.cpp
- src/feedback.cpp
- test/diag.t
Restore commits which are currently not applied to the 2.6.0, but were to 2.5.3.
> Restore commits with lost content
